import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='h-full'>
      <body
        className={cn(
          'relative h-full font-sans antialiased text-gray-900 tracking-tight',
          inter.className
        )}
      >
        <main className='relative flex flex-col min-h-sreen'>
          <ClerkProvider>
            <Providers>
              <Navbar />
              <div className='flex-grow flex-1 min-h-screen overflow-x-hidden'>
                {children}
              </div>
              <Footer />
            </Providers>
          </ClerkProvider>
        </main>
        <Toaster position='top-center' richColors />
      </body>
    </html>
  )
}
